;;; early-init.el --- Early startup configuration
;;; Commentary:
;; Minimal early initialization for Emacs 28.1 to prevent GUI flickering.
;; Only GUI settings are included; other settings are in init.el or config.org.
;; Synced via https://github.com/chaicurioquest/emacs-config.
;; Author: Generated by Grok 3, 2025-07-03.

(when (getenv "MY_DEBUG_DEVICE")
  (message "=== EARLY-INIT START ==="))

;; Increase GC threshold early for faster startup
(setq gc-cons-threshold (* 100 1024 1024))

;; Disable package.el early (use straight.el)
(setq package-enable-at-startup nil)

;; Disable GUI elements early to prevent flickering in graphical Emacs.
(when (display-graphic-p)
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1))

(when (getenv "MY_DEBUG_DEVICE")
  (message "=== EARLY-INIT COMPLETE ==="))