;;; init.el --- Bootstrap Emacs config.org
;;; Commentary:
;; Minimal bootstrapper for Emacs 28.1 configuration.
;; Loads config.el (tangled from config.org) or tangles config.org if needed.
;; Sets early optimizations (GC, package.el) for faster startup.
;; Synced via https://github.com/chaicurioquest/emacs-config.
;; Author: Generated by Grok 3, 2025-07-06.

(when (getenv "MY_DEBUG_DEVICE")
  (message "=== init.el STARTING ==="))

;; Speed up startup by increasing garbage collection threshold to 50MB.
(setq gc-cons-threshold (* 50 1000 1000))

;; Disable package.el to prevent loading before straight.el.
(setq package-enable-at-startup nil)

;; Define paths
(defvar my-config-org (expand-file-name "config.org" user-emacs-directory)
  "Path to main configuration file.")
(defvar my-config-el (expand-file-name "config.el" user-emacs-directory)
  "Path to generated configuration file.")

;; Ensure org is loaded for tangling
(require 'org)

;; Tangle config.org if config.el is missing or outdated
(condition-case err
    (when (or (not (file-exists-p my-config-el))
              (file-newer-than-file-p my-config-org my-config-el))
      (message "Tangling %s to %s..." my-config-org my-config-el)
      (org-babel-tangle-file my-config-org my-config-el)
      (message "Tangled successfully."))
  (error (message "Error tangling config.org: %s" err)))

;; Load config.el
(condition-case err
    (when (file-exists-p my-config-el)
      (load my-config-el))
  (error (message "Error loading config.el: %s" err)))

(when (getenv "MY_DEBUG_DEVICE")
  (message "=== init.el COMPLETE ==="))